spring.application.name=reel-service

# Database Connection (H2)
spring.datasource.url=jdbc:h2:mem:feediodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=feedio_db
spring.datasource.password=
spring.h2.console.enabled=true

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Force Spring Boot to run data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always